services:
  marketbot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: marketbot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./config.json:/Mod/config.json:ro
      - "D:/DualUniverseServer/config/dual.yaml:/config/dual.yaml:ro"
      - ./logs:/logs
    networks:
      - dualuniverseserver_vpcbr
  
  loki:
    image: grafana/loki
    ports:
        - "3100:3100"
    command: -config.file=/etc/loki/loki-config.yaml
    volumes:
      - ./monitoring/loki/loki-config.yaml:/etc/loki/loki-config.yaml:ro
    networks:
        - dualuniverseserver_vpcbr
  
  grafana:
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_HIDE_VERSION=true
      - GF_FEATURE_TOGGLES_ENABLE=alertingSimplifiedRouting,alertingQueryAndExpressionsStepMode
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy 
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        EOF
        /run.sh
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    networks:
      - dualuniverseserver_vpcbr

  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    restart: unless-stopped
    command: 
      - "run"
      - "--storage.path=/var/lib/alloy/data"
      - "/etc/alloy/config.alloy"
    volumes:
      - ./monitoring/grafana/config.alloy:/etc/alloy/config.alloy:ro
      - ./logs:/var/log/marketbot:ro  # Mount MarketBot logs directory
      - /var/run/docker.sock:/var/run/docker.sock:ro  # For Docker logs collection
      - alloy-data:/var/lib/alloy/data  # Persistent storage for Alloy
    networks:
      - dualuniverseserver_vpcbr
    depends_on:
      - loki


volumes:
  alloy-data:
    driver: local

networks:
  dualuniverseserver_vpcbr:
    external: true
